port: 8000
name: bloom-560m
route_prefix: /bloom-560m
num_replicas: 1
cpus_per_worker: 1
gpus_per_worker: 0
deepspeed: false
vllm:
  enabled: true
  precision: fp32
workers_per_group: 2
device: CPU
ipex:
  enabled: false
  precision: bf16
model_description:  
  model_id_or_path: bigscience/bloom-560m
  tokenizer_name_or_path: bigscience/bloom-560m
  chat_template: "llm_on_ray/inference/models/templates/template_gpt2.jinja"
