port: 8000
name: mpt-7b
route_prefix: /mpt-7b
num_replicas: 1
cpus_per_worker: 24
gpus_per_worker: 0
deepspeed: false
workers_per_group: 2
device: cpu
ipex:
  enabled: true
  precision: bf16
model_description:
  model_id_or_path: mosaicml/mpt-7b
  tokenizer_name_or_path: EleutherAI/gpt-neox-20b
  config:
    trust_remote_code: true
